/**
 * Copyright (C) 2026 Cursor Boston
 * This file is part of Cursor Boston, licensed under GPL-3.0.
 * See LICENSE file for details.
 */

/**
 * Auto-generated. DO NOT EDIT BY HAND.
 *
 * Regenerated by `scripts/build-hero-backstory-index.ts` whenever a
 * `.md` file is added to or removed from this directory. The set is
 * consumed by `lib/game/hero-visibility.ts:applyHeroVisibility` to
 * stamp `hasBackstory: boolean` on each hero in API responses, so the
 * UI can show "Read the chronicle" vs "Add the first chapter →".
 *
 * Contributors: add a chapter by creating or editing
 * `lib/game/content/hero-backstories/<heroId>.md` and submitting a PR.
 * The append-only lint (scripts/check-hero-backstory-append-only.js) is
 * run in CI and rejects edits to previously-merged chapters.
 */

export const HERO_BACKSTORY_IDS: ReadonlySet<string> = new Set<string>([

]);
