/**
 * SPDX-License-Identifier: GPL-3.0-only
 * Copyright (C) 2026 Cursor Boston
 * This file is part of Cursor Boston, licensed under GPL-3.0.
 * See LICENSE file for details.
 */

// Stock narrative lines for arming a defense spell on a tile. The line is
// followed by structured outcome (which spell, which tile).
const HUMAN_SPELL_ARM_NARRATIVES: string[] = [
  "Your battlemages walk the perimeter and chant the syllables that turn dirt into ward.",
  "A circle of salt is laid down by hand; it does not blow away in the wind.",
  "The mage-captain inscribes a sigil into the keystone of the tile and steps back without looking.",
  "Three nights of preparation, and now the spell sits quietly in the soil, waiting.",
  "An apprentice trembles as she reads the binding aloud; the spell holds anyway.",
  "The wind around the tile turns once, slow, and then sets back to the prevailing direction. The ward is set.",
  "A row of stones is placed at intervals along the boundary; each one hums when the work is done.",
  "The mage-captain pricks her thumb against the sigil-stone and the air tightens by one notch.",
  "Birds quiet around the tile until the spellwork is finished. They start singing again right after.",
  "A faint scent of iron rises from the soil, then fades. The spell is bedded in.",
  "The villagers know not to walk near the warded stone for a full day after the work is done.",
  "An old veteran walks the perimeter with a candle that won't blow out. The spell follows the candle.",
  "The mage-captain finishes the binding and lets out a breath she has been holding all afternoon.",
  "An owl lands on the warded stone and refuses to be shooed away. The mages take it as a good sign.",
  "A line of frost forms briefly along the boundary even though it is summer. The frost lingers, then sinks into the earth.",
  "The cart that delivered the components leaves with one less horse than it arrived with. No one explains.",
  "A loop of fine wire is stretched across the door of the warded outpost; if it breaks, every mage in camp will know.",
  "The mage-captain scolds an apprentice for sloppy lettering and starts the binding over from the third line.",
  "By dusk the spellwork is done, and the air over the tile feels like a held note that won't quite resolve.",
  "Children playing near the warded boundary find their kites won't fly within twenty paces. They take it as a game.",
  "A drop of oil is placed on each cardinal point of the tile. The drops shine for an hour and then dry.",
  "The spell is laid down so quietly that even the captain doesn't know exactly when it took.",
  "A small brass bell is hung on a post; if the spell triggers, the bell will ring on its own.",
  "An old grimoire is opened to a page no apprentice has been allowed to see, and the binding is read aloud.",
  "Soldiers passing the warded stone make the warding sign without thinking, the way one tips a hat.",
  "The mage-captain refuses tea while the binding sets. It is the only sign that the work is hard.",
  "A quiet rain falls during the casting, then stops the moment the binding takes hold.",
  "The villagers leave a small offering at the warded stone the next morning. It is gone by noon.",
  "Three apprentices hold the components steady; the captain ties them off with a single word.",
  "By the time the moon rises, the spell is locked in. Anyone unfamiliar will feel only a slight weight in the air.",
  "An old soldier mutters that he has seen this kind of warding break two armies. The captain doesn't correct him.",
  "A copper ring is buried beneath the warded stone. No one will dig it up unless something terrible happens.",
  "The captain steps off the tile and the air closes behind her like a curtain.",
  "A spider builds a web across the warded doorway overnight. The mages take this as confirmation that nothing has come through.",
  "The mage-captain claps her hands once. The spell is set. The crew packs up without a word.",
  "Pipe smoke rises straight up from the captain's lips even though the wind is moving. The ward is taking hold.",
  "An old farmer offers his prized boar as payment. The captain refuses but accepts a sack of flour.",
  "The binding is done in the local tongue, with one foreign word at the end that no one quite catches.",
  "A row of candles burns down at the same rate as the binding takes effect. When the last goes out, the work is done.",
  "Lightning splits the sky a mile to the west; the captain doesn't even look up. The spell is more interesting.",
  "A kestrel circles overhead three times and then leaves. The captain notes this in her ledger.",
  "The mage-captain wipes chalk dust from her hands and signs the binding into the work-book.",
  "A small dog runs onto the warded tile, stops dead, sneezes once, and trots away.",
  "The whole crew shares a single loaf of bread when the binding is done. It tastes better than any of them remember.",
  "A handful of salt is thrown to each cardinal point. The salt does not land where it should.",
  "The spell is set, and a stillness comes over the tile that takes the rest of the day to lift.",
  "An old soldier takes off his helm and stands with his head bowed during the binding. No one asks why.",
  "A child's drawing of a dragon is found tucked under the warded stone. The captain leaves it there.",
  "The captain's hands shake briefly as she finishes the binding. She closes her fist and the trembling stops.",
  "By morning the dew on the warded tile has formed a perfect ring. The villagers know not to step on it.",
];

const AI_SPELL_ARM_NARRATIVES: string[] = [
  "An apprentice mage drops her chalk; the captain catches it before it touches the ground and nods her on.",
  "A copper coin is buried at each of the four corners. None of them tarnish over the course of the binding.",
  "The mage-captain hums under her breath through the entire working; the apprentices match her on the third measure.",
  "A torch is lit at sundown and burns through the binding without growing shorter.",
  "Three runes are carved into a beam above the door; the carver wets her thumb and presses it into the last cut.",
  "A small boy is sent away with a coin and a warning; he comes back the next morning with both.",
  "The mage-captain's apprentice reads the third line wrong; the captain corrects her with one finger to the page.",
  "A wreath of holly is laid against the warded post; it does not wither for the next week.",
  "The wind around the tile dies as the binding takes; the trees go absolutely still for the count of seven.",
  "A line of salt is poured along the threshold; it does not blow away even when a cart passes.",
  "The mage-captain places a single gold coin on the warded stone; it darkens to the color of pewter and stays.",
  "An owl in a nearby tree hoots three times during the binding; the captain notes the time.",
  "A scrap of parchment is burned at the corner of the tile; the smoke writes a word in the air, then fades.",
  "The captain whispers to the warded post; the post is silent, but the captain seems satisfied.",
  "A bell is rung once at the start of the binding and once at the end; in between there is no sound at all.",
  "Six candles are lit and arranged in a hexagon; they burn down at exactly the same rate.",
  "A loop of horsehair is laid over the threshold; the apprentice swears she sees it tighten when the binding takes.",
  "An iron nail is driven into the post; the smith's apprentice does it on the third strike and the captain nods.",
  "The mage-captain reads the last line aloud; the air seems to thicken for a heartbeat and then resume its color.",
  "A small dish of milk is left at the warded stone; in the morning it is dry but not spilled.",
  "Three colored ribbons are tied to a branch above the post; the colors are red, white, and a green so dark it is almost black.",
  "An old veteran walks the perimeter once with his hand on the hilt of his sword; he does not draw it.",
  "The mage-captain unlaces her sleeves to her elbows for the binding; she relaces them after.",
  "A flat stone is set at the threshold; the captain steps over it and the air resists for an instant.",
  "Two apprentices hold a length of cord taut across the doorway; the captain cuts it with a single word.",
];

export const SPELL_ARM_NARRATIVES: string[] = [
  ...HUMAN_SPELL_ARM_NARRATIVES,
  ...AI_SPELL_ARM_NARRATIVES,
];
