/**
 * SPDX-License-Identifier: GPL-3.0-only
 * Copyright (C) 2026 Cursor Boston
 * This file is part of Cursor Boston, licensed under GPL-3.0.
 * See LICENSE file for details.
 */

// Stock narrative lines for casting a production spell. Production spells
// affect the player globally for 100 turns, so the narrative leans toward
// "something has shifted" rather than "this specific tile."
const HUMAN_SPELL_PRODUCE_NARRATIVES: string[] = [
  "Your battlemages convene at dusk and read the working aloud, voices rising and falling in unison.",
  "A great brass bell is rung once at the capital, and the mages take this as the moment the spell takes hold.",
  "Tonight the lamps in your camp burn a little brighter, and no one is quite sure why.",
  "The crops in the eastern fields stand a finger's-width taller by morning. The farmers don't comment but they notice.",
  "A column of blue smoke rises from the high tower for an hour and then settles into the evening air.",
  "An old chant is sung in the temple. The chant has not been heard in a generation, but the mages know it.",
  "Your captains report that the troops slept better than usual. They cannot explain why.",
  "Wells across the territory run a hair clearer in the morning. The villagers fill more buckets than usual.",
  "The mage-council finishes the binding at midnight; a single torch flares at the same moment, in every camp.",
  "A flock of crows passes over the capital in formation. The chief mage takes this as proof the work has taken.",
  "Forge-fires burn one shade brighter for the next hundred turns. The smiths don't ask; they just work.",
  "The mage-captain reads the final word and the air in the tower sighs out slowly.",
  "A copper coin is placed on each of your battle-standards as a charm. They will be removed when the spell expires.",
  "A faint warmth settles across your territory like the first hour of spring after a long winter.",
  "The tower's bells ring without being rung. Three short, two long. The mages note the time.",
  "Tonight there is wine in the camp, and the wine tastes better than it has any right to.",
  "A storm to the west breaks just before reaching your border, and turns aside as if politely waved off.",
  "Your scouts report seeing more deer in the woods than usual. The chief mage smiles privately.",
  "The chief mage sleeps for the first time in three days; her work is done, and the working will hold.",
  "The mage-captain unbinds her hair, lets out a long breath, and walks alone to the river.",
  "A soft hum, just at the edge of hearing, settles over the capital for the next hour.",
  "Your apothecary reports that her tinctures have set faster than usual today. She doesn't ask why.",
  "An old healer presses her ear to the ground and nods, satisfied. The work has taken root.",
  "Lamp-flames bow once toward the chief mage's tower, then stand straight again.",
  "The day's bread rises a little higher than usual; the bakers cross themselves and keep working.",
  "A pair of swans glides up the river and lands on the temple pond. The mages let them stay.",
  "The mage-council disperses without speaking. The work needs no announcement.",
  "Your scouts report a strange quiet on the borders, the kind that comes when nothing dares move.",
  "A child sees a star fall over the capital and tells her mother. Her mother nods and goes back to work.",
  "The mage-captain folds the working into her cloak and walks out into the night.",
  "Morning bread, morning water, morning roll-call — all of it goes a little smoother than usual.",
  "A sense of patience settles over the troops; the line stands a little straighter at parade.",
  "The chief mage signs the working into the great book and closes the cover with both hands.",
  "Three apprentices watch the spell take hold, and only one of them has the wit to look pleased.",
  "Your standards snap a little harder in the wind tonight, even when the air is still.",
  "A captain reports that her squad sang on the march for the first time in months. She doesn't know why.",
  "An old story is told around the fire — one nobody has remembered in years. The fire burns slow and warm.",
  "A page falls out of the great working-book. The chief mage picks it up and tucks it carefully back in.",
  "The chief mage looks tired. She refuses tea. She accepts a chair, and watches the moon for an hour.",
  "By the time the spell takes hold, no one in the capital can quite say when it began.",
  "A line of geese passes overhead in a perfect arrowhead. The chief mage notes the direction in her log.",
  "Coin counters report that the day's tally came out cleaner than usual. They do not investigate further.",
  "The mage-captain steps onto the temple roof and watches the working settle over the city like a slow snowfall.",
  "Tonight no one in the capital has a nightmare. The chief mage takes this as confirmation.",
  "The garrison's horses stand quietly through the casting; some of them turn their heads toward the tower as if listening.",
  "A column of butterflies crosses the temple courtyard on its way somewhere else. The mages let them pass.",
  "The mage-council toasts the working in plain water. The water tastes faintly of the river at sunrise.",
  "A storm in the distance flickers but does not arrive. The mages have many such storms to thank.",
  "The chief mage walks home in the rain and is not wet when she arrives.",
  "By dawn the working is laid; by dusk the world has shifted by one small notch in your favor.",
];

const AI_SPELL_PRODUCE_NARRATIVES: string[] = [
  "The chief mage burns a single page from the great working-book; the ash drifts upward instead of down.",
  "A line of bells in the temple courtyard ring once each in sequence as the working settles.",
  "The mage-council closes the casting with a single word; everyone in the room exhales at the same moment.",
  "A faint smell of cedar fills the temple as the working takes; the smell lingers for a day.",
  "The chief mage sets down her staff and stretches her hands until the knuckles crack; she smiles.",
  "A trio of apprentices watches the casting from the doorway; one of them is clearly keeping notes.",
  "The temple's torches burn pale gold through the binding and return to amber when the working is done.",
  "A messenger arrives at the temple just as the casting ends; he is told to come back tomorrow.",
  "The chief mage's familiar — a small grey cat — sleeps through the entire working and wakes the moment it ends.",
  "Tonight the kitchen-fires hold their heat longer than usual; the cooks notice without comment.",
  "Your standards across the territory all turn south at once for a single heartbeat, then resume their previous direction.",
  "The temple's water-clock skips a tick during the binding; the chief mage notes this in her log.",
  "A small bird flies through the temple window during the casting; it lands on the chief mage's shoulder and stays.",
  "Wax from the working candles pools in a perfect six-pointed star; it stays that shape until morning.",
  "The chief mage's apprentices wash the casting tools in cold water; the water steams faintly.",
  "Smoke from the temple's brazier rises in a tight spiral for the duration of the working.",
  "A line of footprints appears in the dust of the temple floor and is gone by the next morning.",
  "An old story-teller in the city pauses mid-sentence as the working takes; he resumes a moment later in a different tale.",
  "The chief mage rests her hand on the temple's central stone; the stone is warm where it should be cool.",
  "A flock of pigeons rises from the temple roof at the moment of binding and circles three times.",
  "The temple's bells ring once on their own; the bell-ringer is asleep in his quarters.",
  "An apprentice falls asleep during the binding; the chief mage covers her with a cloak and continues without comment.",
  "A page in the working-book glows faintly for an instant; only the chief mage sees it, and she does not say so.",
  "The casting ends and the chief mage opens the temple doors; outside, the air is fresh and the night is clear.",
  "A scribe records the casting in three separate ledgers; she signs each one with a different pen.",
];

export const SPELL_PRODUCE_NARRATIVES: string[] = [
  ...HUMAN_SPELL_PRODUCE_NARRATIVES,
  ...AI_SPELL_PRODUCE_NARRATIVES,
];
