/**
 * SPDX-License-Identifier: GPL-3.0-only
 * Copyright (C) 2026 Cursor Boston
 * This file is part of Cursor Boston, licensed under GPL-3.0.
 * See LICENSE file for details.
 */

type ClassNameTree = {
  readonly [key: string]: string | ClassNameTree;
};

export const TAILWIND_CLASS_NAMES = {
  layout: {
    absolute: "absolute",
    block: "block not-a-class",
    flex: "flex",
    flex1: "flex-1",
    flexCol: "flex-col",
    flexWrap: "flex-wrap",
    grid: "grid",
    hFull: "h-full",
    inlineBlock: "inline-block",
    inlineFlex: "inline-flex",
    inset0: "inset-0",
    itemsCenter: "items-center",
    itemsStart: "items-start",
    justifyBetween: "justify-between",
    justifyCenter: "justify-center",
    minW0: "min-w-0",
    overflowHidden: "overflow-hidden",
    relative: "relative",
    shrink0: "shrink-0",
    srOnly: "sr-only",
    truncate: "truncate",
    wFull: "w-full",
    margin_left2: "-ml-2"
  },
  spacing: {
    gap1: "gap-1",
    gap1_5: "gap-1.5",
    gap2: "gap-2",
    gap3: "gap-3",
    gap4: "gap-4",
    mb0_5: "mb-0.5",
    mb1: "mb-1",
    mb2: "mb-2",
    mb3: "mb-3",
    mb4: "mb-4",
    mlAuto: "ml-auto",
    mt1: "mt-1",
    mt2: "mt-2",
    mt3: "mt-3",
    p1: "p-1",
    p2: "p-2",
    p3: "p-3",
    p4: "p-4",
    p6: "p-6",
    pb3: "pb-3",
    p_left4: "pl-4",
    pt3: "pt-3",
    pt4: "pt-4",
    px2: "px-2",
    px3: "px-3",
    px4: "px-4",
    py05: "py-0.5",
    py1: "py-1",
    py2: "py-2",
    py3: "py-3",
    whitespacePreWrap: "whitespace-pre-wrap",
    space_y3: "space-y-3",
  },
  radius: {
    full: "rounded-full",
    lg: "rounded-lg",
    md: "rounded-md",
    plain: "rounded",
    xl: "rounded-xl",
    twoXl: "rounded-2xl",
  },
  border: {
    base: "border",
    bottomNeutral: "border-b border-neutral-200 dark:border-neutral-800",
    emerald: "border-emerald-300/70 dark:border-emerald-500/40",
    emeraldSoft: "border-emerald-300/40 dark:border-emerald-500/30",
    emerald500_50: "border-emerald-500/50",
    emeraldSoft2: "border border-emerald-500/30",
    inputDark: "border border-neutral-700",
    neutral: "border border-neutral-200 dark:border-neutral-800",
    neutralSoft: "border-neutral-200 dark:border-neutral-700",
    neutral_l2: "border-l-2 border-neutral-200 dark:border-neutral-800",
    topNeutral: "border-t border-neutral-200 dark:border-neutral-800",
    purpleSoft: "border border-purple-500/30",
    l4: "border-l-4",
  },
  surface: {
    amberSoft: "bg-amber-500/15",
    blueSoft: "bg-blue-500/10",
    cyanSoft: "bg-cyan-500/10",
    card: "bg-white dark:bg-neutral-900",
    dangerSoft: "bg-red-500/10",
    discord: "bg-[#5865F2]",
    discordSubtle: "bg-[#5865F2]/10",
    emerald: "bg-emerald-500",
    emeraldSoft: "bg-emerald-500/10",
    emerald2: "bg-emerald-700",
    emerald3Hover: "hover:bg-emerald-800",
    hover80Trans: "hover:opacity-80 transition-opacity",
    inputDark: "bg-neutral-800",
    normal: "bg-white dark:bg-neutral-900",
    neutralSoft: "bg-neutral-100 dark:bg-neutral-800",
    neutralSubtle: "bg-neutral-50 dark:bg-neutral-800/40",
    neutral2: "bg-neutral-100 dark:bg-neutral-800/50",
    neutralSubtle2: "bg-neutral-50 dark:bg-neutral-800/50",
    neutralSoftHover: "hover:bg-neutral-100 dark:hover:bg-neutral-800",
    overlay: "bg-black/40",
    purpleSoft: "bg-purple-500/10",
    purpleSubtle: "bg-purple-900/50",
  },
  text: {
    accent: "text-emerald-600 dark:text-emerald-400",
    accentHover: "hover:text-emerald-600 dark:hover:text-emerald-400",
    accentSharpHover: "hover:text-emerald-700 dark:hover:text-emerald-400",
    accentSharp: "text-emerald-700 dark:text-emerald-400",
    accentSharperHover: "hover:text-emerald-800 dark:hover:text-emerald-300",
    amber1: "text-amber-800 dark:text-amber-300",
    blue1: "text-blue-600 dark:text-blue-400",
    body: "text-neutral-700 dark:text-neutral-300",
    cyan1: "text-cyan-600 dark:text-cyan-400",
    danger: "text-red-500",
    dangerSoft: "text-red-400",
    discord: "text-[#5865F2]",
    foreground: "text-foreground",
    inverse: "text-white",
    lg: "text-lg",
    medium: "font-medium",
    muted: "text-neutral-600 dark:text-neutral-400",
    normal: "text-neutral-900 dark:text-white",
    normalHover: "hover:text-neutral-900 dark:hover:text-white",
    gray1Hover: "hover:text-neutral-900 dark:hover:text-neutral-300",
    gray400: "text-neutral-400",
    placeholderGray400: "placeholder-neutral-400",
    purple1: "text-purple-600 dark:text-purple-400",
    red: "text-red-700 dark:text-red-400",
    redHover: "hover:text-red-800 dark:hover:text-red-300",
    redHover2: "hover:text-red-700 dark:hover:text-red-400",
    semibold: "font-semibold",
    sm: "text-sm",
    subtle: "text-neutral-500 dark:text-neutral-400",
    tiny: "text-xs",
    uppercase: "uppercase",
    wide: "tracking-wider",
    wrapBreakWord: "wrap-break-word",
  },
  focus: {
    emerald: "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-400",
    emerald500: "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500",
    emerald700Dark400: "focus-visible:outline-none focus-visible:text-emerald-700 dark:focus-visible:text-emerald-400",
    foregroundEmerald: "focus: outline-none focus: ring-2 focus: ring-emerald-400",
    foreground: "focus:outline-none focus:ring-2 focus:ring-foreground",
    input: "focus:outline-none focus:ring-2 focus:ring-emerald-400 focus:border-transparent",
    inputForeground: "focus:outline-none focus:ring-2 focus:ring-foreground/20 focus:border-transparent",
    neutral: "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-neutral-900 dark:focus-visible:ring-white",
  },
  motion: {
    colors: "transition-colors",
    all: "transition-all",
    duration200: "duration-200",
  },
  state: {
    cursorNotAllowed: "cursor-not-allowed",
    cursorPointer: "cursor-pointer",
    disabled: "opacity-50 cursor-not-allowed",
    disabledSoft: "disabled:opacity-40 disabled:cursor-not-allowed",
    disabledSoftLess: "disabled:opacity-50 disabled:cursor-not-allowed",
    hoverNeutral: "hover:bg-neutral-100 dark:hover:bg-neutral-800",
    hoverNeutralText: "hover:text-neutral-600 dark:hover:text-neutral-300",
  },
  sizing: {
    control44: "min-w-[44px] min-h-[44px]",
    iconXs: "h-3.5 w-3.5",
    iconSm: "h-4 w-4",
    iconMd: "h-5 w-5",
    item14: "w-14 h-14",
    lineClamp3: "line-clamp-3",
    minh44: "min-h-[44px]",
    minw44: "min-w-[44px]",
    noResize: "resize-none",
    voteColumn: "min-w-[40px]",
  },
} as const satisfies ClassNameTree;

const T = TAILWIND_CLASS_NAMES;

export const CLASS_GROUPS = {
  general: {
    flexMid: "flex items-center",
    wPreWrapBreakWord: `${T.spacing.whitespacePreWrap} ${T.text.wrapBreakWord}`
  },
  badge: {
    basePill: `${T.layout.shrink0} ${T.spacing.px2} ${T.spacing.py05} ${T.radius.full} ${T.text.tiny} ${T.text.medium}`,
    earnedPill: `${T.surface.emeraldSoft} ${T.text.accent}`,
    lockedPill: "bg-neutral-200/80 dark:bg-neutral-800 text-neutral-600 dark:text-neutral-400",
    spacing21: `${T.spacing.px2} ${T.spacing.py1}`,
    shade_purple: `${T.surface.purpleSoft} ${T.text.purple1}`,
    shade_blue: `${T.surface.blueSoft} ${T.text.blue1}`,
    shade_cyan: `${T.surface.cyanSoft} ${T.text.cyan1}`,
    shade_amber: `${T.surface.amberSoft} ${T.text.amber1}`,
    small_round_center: "text-xs rounded-full inline-flex items-center gap-1"
  },
  button: {
    iconAction: `${T.spacing.p1} ${T.radius.plain} ${T.motion.colors} ${T.focus.emerald500}`,
    iconLink: `text-neutral-500 hover:text-neutral-900 dark:text-neutral-400 dark:hover:text-white ${T.motion.colors} ${T.focus.neutral} ${T.radius.plain} ${T.spacing.p2} ${T.sizing.control44} ${T.layout.flex} ${T.layout.itemsCenter} ${T.layout.justifyCenter}`,
    neutral: `bg-neutral-100 text-neutral-700 hover:bg-neutral-200 dark:bg-neutral-800 dark:text-neutral-300 dark:hover:bg-neutral-700 ${T.motion.colors} ${T.focus.emerald}`,
    positioning1: `${T.sizing.control44} ${T.layout.flex} ${T.layout.itemsCenter}`,
    size32: `${T.spacing.px3} ${T.spacing.py2}`,
  },
  card: {
    neutral: `${T.surface.card} ${T.radius.xl} ${T.border.neutral}`,
    neutralHover: "hover:border-neutral-300 dark:hover:border-neutral-700",
  },
  form: {
    errorText: `${T.text.dangerSoft} ${T.text.sm} ${T.spacing.mt2}`,
    inputDark: `${T.layout.wFull} ${T.spacing.px4} ${T.spacing.py3} ${T.surface.inputDark} ${T.border.inputDark} ${T.radius.lg} ${T.text.inverse} placeholder-neutral-400 ${T.focus.input}`,
    inputLightDark: `${T.layout.wFull} ${T.spacing.px4} ${T.spacing.py3} ${T.surface.neutralSoft} ${T.border.inputDark} ${T.radius.lg} ${T.text.foreground} text-base placeholder-neutral-400 ${T.focus.inputForeground}`,
    labelDark: `${T.layout.block} ${T.text.sm} ${T.text.medium} text-neutral-300 ${T.spacing.mb2}`,
  },
  status: {
    negativeScore: T.text.danger,
    positiveScore: T.text.accent,
    neutralScore: "text-neutral-500",
  },
  tag: {
    neutral: `${T.spacing.px2} ${T.spacing.py05} ${T.surface.neutralSoft} ${T.text.muted} ${T.radius.plain} ${T.text.tiny}`,
    neutralPill: "px-2.5 py-1 bg-neutral-100 dark:bg-neutral-800 text-neutral-600 dark:text-neutral-400 text-xs font-medium rounded-full",
    neutralStrongPill: "px-2.5 py-1 bg-neutral-200 dark:bg-neutral-800 text-neutral-700 dark:text-neutral-300 text-xs font-medium rounded-full",
    successPill: "px-2.5 py-1 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 text-xs font-medium rounded-full",
  },
  text: {
    body: `${T.text.sm} ${T.text.body}`,
    metadata: `${T.text.tiny} text-neutral-500`,
    muted: `${T.text.sm} ${T.text.muted}`,
    sectionLabel: `${T.text.tiny} ${T.text.uppercase} ${T.text.wide} ${T.text.subtle}`,
  },
  vote: {
    column: `${T.layout.flex} ${T.layout.flexCol} ${T.layout.itemsCenter} ${T.spacing.gap1} ${T.sizing.voteColumn}`,
    disabled: T.state.disabled,
    inactive: "text-neutral-400 hover:text-neutral-600 dark:hover:text-neutral-300",
    score: `${T.text.sm} ${T.text.semibold}`,
  },
} as const satisfies ClassNameTree;
