#!/usr/bin/env bash
# Cloud Agent update script (see https://cursor.com/docs/cloud-agent/setup.md).
# Runs from the repository root. Must be idempotent.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

npm ci

if [[ ! -f .env.local.example ]]; then
  echo "cloud-agent-setup: npm ci complete; .env.local.example missing, skipped .env.local sync."
  exit 0
fi

node <<'NODE'
const fs = require("fs");
const path = require("path");

const exPath = path.join(process.cwd(), ".env.local.example");
const outPath = path.join(process.cwd(), ".env.local");
const ex = fs.readFileSync(exPath, "utf8");

const out = [
  "# Generated by .cursor/scripts/cloud-agent-setup.sh",
  "# Values are copied from the process environment (add matching keys in Cloud Agent secrets).",
  "# Do not commit this file.",
  "",
];

for (const line of ex.split("\n")) {
  const t = line.trim();
  if (!t || t.startsWith("#")) continue;
  const eq = t.indexOf("=");
  if (eq === -1) continue;
  const key = t.slice(0, eq).trim();
  if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) continue;
  if (!Object.prototype.hasOwnProperty.call(process.env, key)) continue;
  const v = process.env[key];
  if (v === undefined) continue;
  const needsQuote =
    /[\s#"'\\]/.test(v) || v.includes("\n") || v.includes("$");
  if (needsQuote) {
    out.push(
      `${key}="${v
        .replace(/\\/g, "\\\\")
        .replace(/"/g, '\\"')
        .replace(/\n/g, "\\n")
        .replace(/\r/g, "\\r")}"`,
    );
  } else {
    out.push(`${key}=${v}`);
  }
}

fs.writeFileSync(outPath, out.join("\n") + "\n");
NODE

echo "cloud-agent-setup: npm ci complete; .env.local synced from environment."
