#!/usr/bin/env node
/**
 * Copyright (C) 2026 Cursor Boston
 * This file is part of Cursor Boston, licensed under GPL-3.0.
 * See LICENSE file for details.
 */

/**
 * Builds `lib/game/content/hero-backstories/_index.ts` from the `.md`
 * files in that directory. Each filename (sans extension) is treated as
 * a hero id and added to the exported `HERO_BACKSTORY_IDS` set.
 *
 * Runs:
 *   - Manually: `npx tsx scripts/build-hero-backstory-index.ts`
 *   - Pre-build: wired into `npm run build` before the OpenAPI gen step
 *
 * Idempotent. Writes the file only if its contents actually change so we
 * don't bust caches needlessly.
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const BACKSTORIES_DIR = join(
  process.cwd(),
  "lib",
  "game",
  "content",
  "hero-backstories"
);
const INDEX_PATH = join(BACKSTORIES_DIR, "_index.ts");

function main(): void {
  const entries = readdirSync(BACKSTORIES_DIR).filter((f) => f.endsWith(".md"));
  const heroIds = entries.map((f) => f.replace(/\.md$/, "")).sort();
  const lines = heroIds.map((id) => `  ${JSON.stringify(id)},`).join("\n");
  const next = `/**
 * Copyright (C) 2026 Cursor Boston
 * This file is part of Cursor Boston, licensed under GPL-3.0.
 * See LICENSE file for details.
 */

/**
 * Auto-generated. DO NOT EDIT BY HAND.
 *
 * Regenerated by \`scripts/build-hero-backstory-index.ts\` whenever a
 * \`.md\` file is added to or removed from this directory. The set is
 * consumed by \`lib/game/hero-visibility.ts:applyHeroVisibility\` to
 * stamp \`hasBackstory: boolean\` on each hero in API responses, so the
 * UI can show "Read the chronicle" vs "Add the first chapter →".
 *
 * Contributors: add a chapter by creating or editing
 * \`lib/game/content/hero-backstories/<heroId>.md\` and submitting a PR.
 * The append-only lint (scripts/check-hero-backstory-append-only.js) is
 * run in CI and rejects edits to previously-merged chapters.
 */

export const HERO_BACKSTORY_IDS: ReadonlySet<string> = new Set<string>([
${lines}
]);
`;
  // No-op write if the content is unchanged so the build step doesn't
  // create churn for clean checkouts.
  let current = "";
  try {
    current = readFileSync(INDEX_PATH, "utf8");
  } catch {
    // First run: file may not exist yet.
  }
  if (current === next) {
    console.log(
      `[build-hero-backstory-index] no change — ${heroIds.length} ids`
    );
    return;
  }
  writeFileSync(INDEX_PATH, next, "utf8");
  console.log(
    `[build-hero-backstory-index] wrote ${INDEX_PATH} (${heroIds.length} ids)`
  );
}

main();
