/**
 * Copyright (C) 2026 Cursor Boston
 * This file is part of Cursor Boston, licensed under GPL-3.0.
 * See LICENSE file for details.
 */

/**
 * Regenerates `docs/API.md` from `public/openapi.json`. Wired into
 * `prebuild` AFTER `generate:openapi`, so the human-readable endpoint
 * table can never drift from the contracts.
 *
 * The output keeps the original 4-column layout (Method | Endpoint |
 * Auth | Description) and groups by tag, matching what
 * `scripts/generate-llms-txt.js` parses.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(__dirname, "..");
const SPEC_PATH = join(ROOT, "public", "openapi.json");
const OUTPUT_PATH = join(ROOT, "docs", "API.md");

interface OperationLike {
  summary?: string;
  description?: string;
  tags?: string[];
  responses?: Record<string, unknown>;
}

interface PathItemLike {
  [method: string]: OperationLike | unknown;
}

interface SpecLike {
  paths: Record<string, PathItemLike>;
  tags?: Array<{ name: string; description?: string }>;
}

const HTTP_METHODS = ["get", "post", "put", "patch", "delete"] as const;

const spec = JSON.parse(readFileSync(SPEC_PATH, "utf8")) as SpecLike;

interface Row {
  method: string;
  path: string;
  auth: "Yes" | "No";
  description: string;
}

const tagOrder: string[] = (spec.tags ?? []).map((t) => t.name);
const byTag = new Map<string, Row[]>();
const tagDescriptions = new Map<string, string>();
for (const t of spec.tags ?? []) {
  if (t.description) tagDescriptions.set(t.name, t.description);
}

for (const [path, item] of Object.entries(spec.paths)) {
  for (const method of HTTP_METHODS) {
    const op = item[method] as OperationLike | undefined;
    if (!op || typeof op !== "object") continue;
    const tag = op.tags?.[0] ?? "other";
    if (!byTag.has(tag)) byTag.set(tag, []);
    byTag.get(tag)!.push({
      method: method.toUpperCase(),
      path,
      auth: op.responses && "401" in op.responses ? "Yes" : "No",
      description: (op.summary ?? "").replace(/\|/g, "\\|"),
    });
  }
}

const orderedTags = [
  ...tagOrder.filter((t) => byTag.has(t)),
  ...[...byTag.keys()].filter((t) => !tagOrder.includes(t)).sort(),
];

const totalOps = [...byTag.values()].reduce((sum, rows) => sum + rows.length, 0);

const out: string[] = [];
out.push("<!--");
out.push("  AUTOGENERATED by scripts/generate-api-md.ts on every build.");
out.push("  Source of truth: public/openapi.json (generated from lib/api-schemas/).");
out.push("  Edit the contracts under lib/api-schemas/, not this file.");
out.push("-->");
out.push("");
out.push("# API Reference");
out.push("");
out.push(
  `All endpoints are under \`/api/\`. Authentication uses Firebase Auth ID tokens (Bearer) or session cookies. Spec: [\`/openapi.json\`](https://cursorboston.com/openapi.json) · interactive: [\`/api/docs\`](https://cursorboston.com/api/docs).`
);
out.push("");
out.push(
  `**${Object.keys(spec.paths).length} paths, ${totalOps} operations across ${orderedTags.length} areas.**`
);
out.push("");
out.push("---");
out.push("");

function tagToHeading(tag: string): string {
  return tag
    .split(/[-/]/)
    .map((s) => (s.length ? s[0].toUpperCase() + s.slice(1) : s))
    .join(" ");
}

for (const tag of orderedTags) {
  const rows = byTag.get(tag)!;
  rows.sort((a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method));
  out.push(`## ${tagToHeading(tag)}`);
  const desc = tagDescriptions.get(tag);
  if (desc) {
    out.push("");
    out.push(`_${desc}._`);
  }
  out.push("");
  out.push("| Method | Endpoint | Auth | Description |");
  out.push("|--------|----------|------|-------------|");
  for (const r of rows) {
    out.push(`| ${r.method} | \`${r.path}\` | ${r.auth} | ${r.description} |`);
  }
  out.push("");
}

writeFileSync(OUTPUT_PATH, out.join("\n"), "utf8");
console.log(
  `[api-md] Wrote ${OUTPUT_PATH} — ${totalOps} operations across ${orderedTags.length} areas.`
);
