/**
 * Copyright (C) 2026 Cursor Boston
 * This file is part of Cursor Boston, licensed under GPL-3.0.
 * See LICENSE file for details.
 */

/** Hero names for the Black caste. Necromantic, shrouded, plural-personae
 *  tone — assassins, oracles, dread-knights. */
export const BLACK_HERO_NAMES: ReadonlyArray<string> = [
  "The Hollow Drask",
  "Karven the Unseeing",
  "Vorrik Coldhand",
  "Mother Crow",
  "Sister Black-Iron",
  "The Pale Tarn",
  "Halrik the Wormtongue",
  "Whispering Olem",
  "Dread-Knight Vurn",
  "The Quiet Ardun",
  "Belzin of the Last Door",
  "Yenn the Mortician",
  "The Twin-Faced Korel",
  "Plague-Bishop Maven",
  "Ardov of the Empty Glove",
  "Wraith-Captain Sehl",
  "Mother of Threads",
  "The Echo of Vask",
  "Karven Again",
  "Sister Funeral",
  "Drennin the Recanted",
  "Praevin the Shroud",
  "Halrik Twice-Buried",
  "Voltaen Black-Mantle",
  "The Faceless Iorn",
  "Mournlord Sehv",
  "Ash-Speaker Erun",
  "The Ninefold Drask",
  "Pale Bishop Korven",
  "Vurn the Reluctant",
  "Sister of the Quiet Pasture",
  "Worm-Lord Belos",
  "Karven Below",
  "Sehl the Returning",
  "Ardov Without Issue",
  "The Mortician Praved",
  "Hollow-Mother Vehs",
  "The Twin Korven",
  "Sister Salt-Mouth",
  "Praevin Reread",
  "Bishop of the Disclosed Door",
  "The Many of Olem",
  "Dread-Lector Vurn",
  "Plague-Sister Maelva",
  "The Pale of the Pale",
  "Karven Outlasting",
  "Yenn Twice-Mortician",
  "The Shroud Recanted",
  "Belzin Reopened",
  "Sister of the Closing Hour",
];
