/**
 * Copyright (C) 2026 Cursor Boston
 * This file is part of Cursor Boston, licensed under GPL-3.0.
 * See LICENSE file for details.
 */

/** Hero names for the Blue caste. Sky-reader, sea-bound, hawkish — scouts,
 *  navigators, weather-walkers. */
export const BLUE_HERO_NAMES: ReadonlyArray<string> = [
  "Sky-Reader Aelis",
  "Navigator Tor",
  "Captain Pellumen",
  "Cordra Sea-Mantle",
  "Astri Cloud-Walker",
  "Sky-Knight Henrik",
  "Mariner Ofelda",
  "Captain Whitewing",
  "Navigator Halris",
  "Cordra of the Long Tack",
  "Sky-Lord Erys",
  "Pellumen the Far-Eye",
  "Astri Returning",
  "Hawk-Captain Vael",
  "Sister Stormglass",
  "Sky-Reader Brennen",
  "Cordra Returned-from-South",
  "Mariner Polenwyn",
  "Captain Sky-Mantle",
  "Navigator of the Cold Strait",
  "Astri Twice-Flown",
  "Sky-Bishop Velin",
  "Pellumen Long-Glass",
  "Captain Aer",
  "Hawk-Sister Brille",
  "Cordra of the Black Sail",
  "Sky-Captain Henrik II",
  "Navigator Helsric",
  "Mariner Calwen",
  "Astri of the Rolling Cloud",
  "Pellumen the Reaching",
  "Sky-Reader Olris",
  "Captain Mistwing",
  "Cordra Patient-Sail",
  "Hawk-Lord Brennen",
  "Astri Sea-Returning",
  "Navigator Pelmer",
  "Sky-Sister Velna",
  "Captain Lance-of-Cloud",
  "Pellumen of the Quiet Ocean",
  "Cordra Three-Crossings",
  "Mariner Hollowmast",
  "Astri the Long-Sighted",
  "Sky-Knight Brennica",
  "Hawk-Reader Olfen",
  "Navigator Twice-Lost",
  "Pellumen the Sure-Hand",
  "Captain Sea-Lantern",
  "Astri of the Final Tack",
  "Cordra Anchor-Mother",
];
