/**
 * SPDX-License-Identifier: GPL-3.0-only
 * Copyright (C) 2026 Cursor Boston
 * This file is part of Cursor Boston, licensed under GPL-3.0.
 * See LICENSE file for details.
 */

/** Hero names for the Green caste. Root, vine, deep-glade — druidic,
 *  ranger-flavored, slow-cooked. */
export const GREEN_HERO_NAMES: ReadonlyArray<string> = [
  "Branwen Root-Speaker",
  "Old Halmer of the Glade",
  "Sister Iva of the Long Vine",
  "Faolan Three-Acorns",
  "Druid Maerdwen",
  "Ranger-Captain Onnis",
  "Vorrin Whisperleaf",
  "Branwen Returning",
  "Wood-Mother Cera",
  "Ranger Aldric",
  "Druid of the First Tree",
  "Sister Birch",
  "Faolan Mossfoot",
  "Halmer of the Pale Fern",
  "Vine-Walker Pess",
  "Onnis Twice-Tracked",
  "Druid-Captain Helsric",
  "Sister Ivory-Bark",
  "Maerdwen Returned",
  "Old Ranger Dunn",
  "Vorrin of the Slow Glade",
  "Branwen the Patient",
  "Faolan Acorn-Eye",
  "Druid Erdwen",
  "Wood-Captain Belris",
  "Ranger of the Quiet Fjord",
  "Onnis of the Patient River",
  "Sister Heather",
  "Halmer Twice-Lost",
  "Branwen Below the Roots",
  "Faolan the Hidden",
  "Druid of the Bone-Bough",
  "Old Erdwen",
  "Ranger Pelhin",
  "Vorrin Long-Memory",
  "Sister Sorrel",
  "Maerdwen of the Black Spruce",
  "Wood-Mother Halma",
  "Druid Brennell",
  "Faolan Lichen-Foot",
  "Old Halmer Reborn",
  "Vine-Sister Brille",
  "Ranger-Captain Aedwen",
  "Druid Sennar",
  "Branwen of the Last Spring",
  "Sister Wormwood",
  "Old Ranger Falst",
  "Wood-Bishop Helvin",
  "Druid of the Twin Oaks",
  "Faolan Returning to Soil",
];
