/**
 * Copyright (C) 2026 Cursor Boston
 * This file is part of Cursor Boston, licensed under GPL-3.0.
 * See LICENSE file for details.
 */

/** Hero names for the Red caste. Forge-mountain, hammer-on-anvil — smiths,
 *  flame-priests, brawlers. */
export const RED_HERO_NAMES: ReadonlyArray<string> = [
  "Hrolfgar Anvil-Wright",
  "Forge-Captain Brunn",
  "Mira the Bellows",
  "Vannik Slag-Mouth",
  "Khorvik of the Red Hand",
  "Drannor Twice-Tempered",
  "Smithmother Helene",
  "Burn-Lord Veska",
  "Hrolfgar Again",
  "Captain Cinder",
  "Forgesworn Polmir",
  "Caska Three-Hammers",
  "Smith-Knight Veld",
  "Inferno-Captain Brun",
  "Mira Returned",
  "Khorvik Cold-Anvil",
  "Drannor of the Long Forge",
  "Ash-Captain Vorum",
  "Forge-Bishop Eldric",
  "Hrolfgar's Daughter",
  "Captain Vassilic",
  "Burn-Sister Polis",
  "Mira of the Heat-Slick Road",
  "Smith-Captain Orvik",
  "Forge-Lord Bruska",
  "Khorvik the Quench-Fast",
  "Vannik of the Cold Hammer",
  "Captain Embergrim",
  "Forge-Knight Helma",
  "Sister Furnace",
  "Hrolfgar the Last",
  "Mira Anvil-Wright",
  "Brunn of the Long Tempering",
  "Forge-Captain Veld",
  "Inferno-Sister Korva",
  "Drannor the Patient",
  "Caska of Three Forges",
  "Ash-Lord Veska",
  "Brun Twice-Quenched",
  "Forge-Smith Polin",
  "Mira the Forge-Daughter",
  "Hrolfgar of the Heatless Anvil",
  "Captain Coal",
  "Smith-Mother Pellen",
  "Burn-Bishop Halris",
  "Drannor the Reforged",
  "Vannik Hot-Iron",
  "Captain Klink",
  "Forge-Sister Aedva",
  "Khorvik Hammer-Tongue",
];
