/**
 * SPDX-License-Identifier: GPL-3.0-only
 * Copyright (C) 2026 Cursor Boston
 * This file is part of Cursor Boston, licensed under GPL-3.0.
 * See LICENSE file for details.
 */

/** Hero names for the White caste. Order-faithful, almost monastic tone
 *  — knights, scholars, paladins. */
export const WHITE_HERO_NAMES: ReadonlyArray<string> = [
  "Sir Ashvane",
  "Dame Lyric",
  "Brother Ondric",
  "Saint Halvor",
  "Lady Erinmoore",
  "Ser Calemir",
  "Mother Veska",
  "High-Knight Pell",
  "Dame Sorin",
  "Brother Velhan",
  "Sister Aldera",
  "Sir Westwind",
  "Lord Tomas",
  "Knight-Errant Briar",
  "Captain Mariel",
  "Dame Theron",
  "Ser Cadwall",
  "Lady Holcombe",
  "Father Esmond",
  "Sir Brennan of the Pale Coast",
  "Dame Wynnefred",
  "Knight-Captain Iselle",
  "Brother Cassian",
  "Ser Hollow",
  "Dame Korvene",
  "Lord Tarrowmoor",
  "Sister Bel",
  "Sir Maerwen",
  "Dame Solinde",
  "High-Lector Pelleas",
  "Ser Thoraine",
  "Lady Aldsworth",
  "Knight-Sworn Edmer",
  "Brother Lucan",
  "Dame Vesper",
  "Ser Hollin",
  "Sir Marrich",
  "Mother Owain",
  "Dame Wrenwell",
  "Sir Caelth",
  "Lady Mireval",
  "Brother Daros",
  "Ser Vance",
  "Dame Ellowyn",
  "Knight-Lector Storne",
  "Sir Albreth",
  "Sister Ivory",
  "Dame Galen",
  "Ser Northwell",
  "Lord Heronwood",
];
